### ISSUE TITLE
Some valid Currency and Country codes rejected

### ISSUE THREAD

**Issue by DanielFEvans** [sr-murthy/oedtools#13]
Some custom codes for Currency and Country defined in the OED specification are rejected by the tool.

Currency: NIS (New Israeli Shekel) is rejected. Tested several historic codes which were all accepted correctly.
Country: All tested offshore codes (e.g. A1) are rejected. The other OED defined codes (XB, XE, XS, XW) are OK.

Using v0.3.2.

**Comment by sr-murthy** [comment]
The (new) Israeli Shekel currency code is ILS not NIS.

https://github.com/sr-murthy/oedtools/blob/master/oedtools/schema/values.csv#L457
https://www.xe.com/currency/ils-israeli-shekel

These currency codes are ISO 4217 currency codes. The same codes are contained in the currency codes sheet in the OED schema spreadsheet

https://github.com/Simplitium/OED/blob/master/Open%20Exposure%20Data%20Spec.xlsx

I'm not sure about offshore codes, but all valid ISO 3166 country codes will be accepted. My guess is these offshore codes are not ISO 3166 country codes.

**Comment by sr-murthy** [comment]
I've just done a file validation test on a PiWind test loc. file (`OasisPiWind/tests/data/SourceLocOEDPiWind10.csv`) with `LocCurrency` set to `ILS` (Israel shekel), and no errors are reported, which is what is expected.

As for country codes, setting `CountryCode` to `A1` however does produce the expected error

    ../OasisPiWind/tests/data/SourceLocOEDPiWind10.csv:4:158: Invalid value "A1" in "CountryCode" - check the column or data type range: OED error: E371 Out of range data found in column

The package uses ISO 3166 country codes, and `A1` is not a valid ISO 3166 country code.

So I don't think there is any problem here, and I will be closing this later today, unless you have something else to report on this.

**Comment by DanielFEvans** [comment]
Please see the Country Currency Values table in the OED specification. These codes are included.

**Comment by sr-murthy** [comment]
Yes, it does look as if there are a number of these non-ISO 3166 offshore country codes in the OED spec. I had assumed ISO 3166 country codes would be used. So the values CSV will have to be updated and then the profile re-generated, and a new package version published.

**Comment by sr-murthy** [comment]
https://github.com/sr-murthy/oedtools/pull/15

**Comment by sr-murthy** [comment]
Version 0.4.2 has been published, which deals with the offshore country codes issue.
